
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class ArquivoPropostaDigital
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ArquivoPropostaDigital()
    {

        this.ArquivoPropostaDigitalDetalhe = new HashSet<ArquivoPropostaDigitalDetalhe>();

    }


    public int idArquivoPropostaDigital { get; set; }

    public System.DateTime dataCadastro { get; set; }

    public string usuario { get; set; }

    public string nomeArquivo { get; set; }

    public int quantidade { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ArquivoPropostaDigitalDetalhe> ArquivoPropostaDigitalDetalhe { get; set; }

}

}
