
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class ArquivoPropostaDigitalDetalhe
{

    public int idArquivoPropostaDigitalDetalhe { get; set; }

    public int idArquivoPropostaDigital { get; set; }

    public int numeroProposta { get; set; }

    public string externalKey { get; set; }

    public int statusProposta { get; set; }

    public string json { get; set; }



    public virtual ArquivoPropostaDigital ArquivoPropostaDigital { get; set; }

    public virtual ControleProposta ControleProposta { get; set; }

}

}
