
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class AtivPessoa
{

    public short cdativpes { get; set; }

    public short tppes { get; set; }

    public string nmativpes { get; set; }

    public string codigoCNAE { get; set; }

}

}
