
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class Colaborador
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Colaborador()
    {

        this.ControleProposta = new HashSet<ControleProposta>();

    }


    public int cdpescol { get; set; }

    public int cdempcol { get; set; }

    public int nrcha { get; set; }

    public string inrecprm { get; set; }

    public short tpfun { get; set; }

    public short cdloc { get; set; }

    public short stcol { get; set; }

    public Nullable<int> cdhier { get; set; }

    public Nullable<short> tphier { get; set; }

    public Nullable<int> cdpescor { get; set; }

    public Nullable<short> cduni { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ControleProposta> ControleProposta { get; set; }

}

}
