
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class ControleDataSistema
{

    public System.DateTime dtultdiaria { get; set; }

    public System.DateTime dtdiariaatual { get; set; }

    public System.DateTime dtultmensal { get; set; }

    public System.DateTime dtproxmensal { get; set; }

    public System.DateTime dtcompetcontab { get; set; }

    public string dtmesrefultcontab { get; set; }

}

}
