
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class ControleProposta
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ControleProposta()
    {

        this.ArquivoPropostaDigitalDetalhe = new HashSet<ArquivoPropostaDigitalDetalhe>();

    }


    public int nrppscor { get; set; }

    public Nullable<int> cdconseg { get; set; }

    public Nullable<System.DateTime> dtprop { get; set; }

    public string nmescritorio { get; set; }

    public string nmusuari { get; set; }

    public decimal nrnossonumero { get; set; }

    public Nullable<int> stprop { get; set; }

    public Nullable<System.DateTime> dtvenda { get; set; }

    public string stmotivo { get; set; }

    public Nullable<System.DateTime> dtstatus { get; set; }

    public Nullable<decimal> vlpretot { get; set; }

    public Nullable<System.DateTime> dtven { get; set; }

    public Nullable<int> cdpescol { get; set; }

    public Nullable<short> incopinter { get; set; }

    public Nullable<System.DateTime> dtcopinter { get; set; }

    public Nullable<short> incopdig { get; set; }

    public Nullable<System.DateTime> dtcopdig { get; set; }



    public virtual Colaborador Colaborador { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ArquivoPropostaDigitalDetalhe> ArquivoPropostaDigitalDetalhe { get; set; }

}

}
