
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class CorretorVigencia
{

    public int cdpescor { get; set; }

    public System.DateTime dataInicioVigencia { get; set; }

    public int cdregsus { get; set; }

    public short cdloc { get; set; }

    public System.DateTime dtregsus { get; set; }

    public string sgufregsus { get; set; }

    public string incomant { get; set; }

    public short tpmeipgt { get; set; }

    public short stcor { get; set; }

    public short tpperpgt { get; set; }

    public int cdorgprt { get; set; }

    public short tporgprt { get; set; }

    public Nullable<int> cdpesins { get; set; }

    public string inplataf { get; set; }

    public Nullable<int> cdpescorpla { get; set; }

    public Nullable<int> cdpesterpla { get; set; }

    public Nullable<System.DateTime> dtvalregsus { get; set; }



    public virtual Pessoa Pessoa { get; set; }

}

}
