

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class DigitacaoEntities : DbContext
{
    public DigitacaoEntities()
        : base("name=DigitacaoEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<TB_CLIENTE> TB_CLIENTE { get; set; }

    public virtual DbSet<TB_CLIENTE_EMAIL> TB_CLIENTE_EMAIL { get; set; }

    public virtual DbSet<TB_CLIENTE_ENDERECO> TB_CLIENTE_ENDERECO { get; set; }

    public virtual DbSet<TB_CLIENTE_TELEFONE> TB_CLIENTE_TELEFONE { get; set; }

    public virtual DbSet<TB_PROPOSTA> TB_PROPOSTA { get; set; }

    public virtual DbSet<TB_DADOS_BANCARIOS> TB_DADOS_BANCARIOS { get; set; }

    public virtual DbSet<TB_DADOS_CARTAO> TB_DADOS_CARTAO { get; set; }

    public virtual DbSet<TB_RESP_PERG_PROPOSTA> TB_RESP_PERG_PROPOSTA { get; set; }

    public virtual DbSet<TB_BENEFICIARIO> TB_BENEFICIARIO { get; set; }

    public virtual DbSet<TB_DOMINIO_CAMPO> TB_DOMINIO_CAMPO { get; set; }

}

}

