
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class InterfaceSinafCobertura
{

    public short cdcobert { get; set; }

    public int cdid { get; set; }

    public string bcf { get; set; }

    public short cdtipofuneral { get; set; }

}

}
