
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class Produto
{

    public short cdprodut { get; set; }

    public string nmprodut { get; set; }

    public string nmaprodu { get; set; }

    public string tpprodut { get; set; }

    public short cdramosg { get; set; }

    public short cdsubram { get; set; }

    public short cdagrupr { get; set; }

    public System.DateTime dtatuali { get; set; }

    public string tpitemsg { get; set; }

    public string tppadimp { get; set; }

    public string idprodtpemi { get; set; }

    public Nullable<short> idprodtppro { get; set; }

}

}
