
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class TB_CLIENTE
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TB_CLIENTE()
    {

        this.TB_CLIENTE_EMAIL = new HashSet<TB_CLIENTE_EMAIL>();

        this.TB_CLIENTE_ENDERECO = new HashSet<TB_CLIENTE_ENDERECO>();

        this.TB_CLIENTE_TELEFONE = new HashSet<TB_CLIENTE_TELEFONE>();

        this.TB_RESP_PERG_PROPOSTA = new HashSet<TB_RESP_PERG_PROPOSTA>();

    }


    public int cd_ctt { get; set; }

    public int cd_prd { get; set; }

    public int nr_ppt { get; set; }

    public int nr_seqcli { get; set; }

    public Nullable<int> cd_agp { get; set; }

    public string ds_agp { get; set; }

    public Nullable<int> nr_pla { get; set; }

    public string ds_pla { get; set; }

    public Nullable<decimal> vl_is { get; set; }

    public Nullable<decimal> vl_isap { get; set; }

    public string nm_nmecli { get; set; }

    public Nullable<decimal> nr_cgccpfcli { get; set; }

    public Nullable<System.DateTime> dt_nsccli { get; set; }

    public Nullable<int> tp_sexocli { get; set; }

    public string ds_sexocli { get; set; }

    public Nullable<byte> st_estcivcli { get; set; }

    public string ds_estcivcli { get; set; }

    public string fl_cpfpoocli { get; set; }

    public Nullable<decimal> cd_mat { get; set; }

    public Nullable<decimal> vl_rdacli { get; set; }

    public string nr_idtcli { get; set; }

    public string dc_orgexdidtcli { get; set; }

    public Nullable<System.DateTime> dt_exd_idtcli { get; set; }

    public int tp_cli { get; set; }

    public Nullable<int> tp_pte { get; set; }

    public Nullable<int> cd_atd { get; set; }

    public Nullable<int> cd_pes { get; set; }

    public Nullable<byte> id_exl { get; set; }

    public Nullable<int> cd_pesdig { get; set; }

    public Nullable<decimal> vl_pmo { get; set; }

    public Nullable<int> tp_tit { get; set; }

    public string nm_nmeclippt { get; set; }

    public Nullable<decimal> vl_isalodtr { get; set; }

    public Nullable<decimal> vl_isdoecgn { get; set; }

    public Nullable<decimal> vl_isgrvinf { get; set; }

    public Nullable<decimal> vl_isdiainf { get; set; }

    public Nullable<decimal> vl_pmoalodtr { get; set; }

    public Nullable<decimal> vl_pmodoecgn { get; set; }

    public Nullable<decimal> vl_pmoprtcri { get; set; }

    public Nullable<decimal> vl_isassemg { get; set; }

    public Nullable<decimal> vl_pmoassemg { get; set; }



    public virtual TB_PROPOSTA TB_PROPOSTA { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TB_CLIENTE_EMAIL> TB_CLIENTE_EMAIL { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TB_CLIENTE_ENDERECO> TB_CLIENTE_ENDERECO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TB_CLIENTE_TELEFONE> TB_CLIENTE_TELEFONE { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TB_RESP_PERG_PROPOSTA> TB_RESP_PERG_PROPOSTA { get; set; }

}

}
