
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class TB_DADOS_CARTAO
{

    public int cd_ctt { get; set; }

    public int cd_prd { get; set; }

    public int nr_ppt { get; set; }

    public bool pri_msl { get; set; }

    public bool dms_msl { get; set; }

    public string tp_cba { get; set; }

    public Nullable<int> cd_bnd { get; set; }

    public string nm_cli { get; set; }

    public string nr_cto { get; set; }

    public string nr_ultnumcto { get; set; }

    public string nr_cvv { get; set; }

    public Nullable<int> nr_mesvct { get; set; }

    public Nullable<int> nr_anovct { get; set; }

    public Nullable<System.DateTime> dt_vctpcl { get; set; }

    public Nullable<decimal> vr_pmo { get; set; }

    public string st_reg { get; set; }

    public Nullable<System.DateTime> dt_icl { get; set; }

    public Nullable<int> id_chvpub { get; set; }

    public Nullable<System.DateTime> dt_pss { get; set; }



    public virtual TB_PROPOSTA TB_PROPOSTA { get; set; }

}

}
