
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class TB_DADOS_BANCARIOS
{

    public int cd_ctt { get; set; }

    public int cd_prd { get; set; }

    public int nr_ppt { get; set; }

    public string nr_bco { get; set; }

    public string nr_agc { get; set; }

    public string nr_dva { get; set; }

    public string nr_cta { get; set; }

    public string nr_dvc { get; set; }

    public string nr_tipcta { get; set; }

    public string nr_catcta { get; set; }

    public string nm_ttlcta { get; set; }

    public string nr_cpfttlcta { get; set; }



    public virtual TB_PROPOSTA TB_PROPOSTA { get; set; }

}

}
