
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class TB_DOMINIO_CAMPO
{

    public string nm_cam { get; set; }

    public string ds_vlrdmn { get; set; }

    public string ds_sgncam { get; set; }
    public string nm_tab { get; set; }


    }

}
