
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class TB_LOG_PROCESSAMENTO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TB_LOG_PROCESSAMENTO()
    {

        this.TB_REGISTRO_PROCESSAMENTO = new HashSet<TB_REGISTRO_PROCESSAMENTO>();

    }


    public int cd_logpss { get; set; }

    public string cd_pss { get; set; }

    public string cd_usu { get; set; }

    public System.DateTime dt_inipss { get; set; }

    public Nullable<System.DateTime> dt_fimpss { get; set; }

    public Nullable<int> qt_minpss { get; set; }

    public Nullable<int> qt_totreg { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TB_REGISTRO_PROCESSAMENTO> TB_REGISTRO_PROCESSAMENTO { get; set; }

}

}
