
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class TB_RESP_PERG_PROPOSTA
{

    public int cd_ctt { get; set; }

    public int cd_prd { get; set; }

    public int nr_ppt { get; set; }

    public int nr_seqcli { get; set; }

    public int nr_ord { get; set; }

    public string ds_obs { get; set; }

    public int cd_pgt { get; set; }

    public string ds_pgt { get; set; }

    public int cd_rsp { get; set; }

    public string ds_rsp { get; set; }

    public Nullable<short> tp_dps { get; set; }



    public virtual TB_CLIENTE TB_CLIENTE { get; set; }

}

}
