
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class TB_REGISTRO_PROCESSAMENTO
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TB_REGISTRO_PROCESSAMENTO()
    {

        this.TB_DETALHE_REGISTRO = new HashSet<TB_DETALHE_REGISTRO>();

        this.TB_ERRO_REGISTRO = new HashSet<TB_ERRO_REGISTRO>();

    }


    public int cd_regpss { get; set; }

    public int cd_logpss { get; set; }

    public string st_regpss { get; set; }

    public Nullable<System.DateTime> dt_sitreg { get; set; }



    public virtual TB_LOG_PROCESSAMENTO TB_LOG_PROCESSAMENTO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TB_DETALHE_REGISTRO> TB_DETALHE_REGISTRO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TB_ERRO_REGISTRO> TB_ERRO_REGISTRO { get; set; }

}

}
