
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class VigCaractProduto
{

    public short cdprodut { get; set; }

    public System.DateTime dtinivig { get; set; }

    public System.DateTime dtfimvig { get; set; }

    public System.DateTime dtlimenq { get; set; }

    public short qtmincof { get; set; }

    public string cdiratis { get; set; }

    public string cdindcen { get; set; }

    public decimal vlprmiap { get; set; }

    public decimal vlprmien { get; set; }

    public decimal vlprmifa { get; set; }

    public decimal vlparmin { get; set; }

    public short qtdiascp { get; set; }

    public short qtdiasem { get; set; }

    public short qtdiaser { get; set; }

    public decimal pcdevfpa { get; set; }

    public decimal pcdevsca { get; set; }

    public decimal pcdepiaa { get; set; }

    public string tprenova { get; set; }

    public short tpcorisr { get; set; }

    public string cdindara { get; set; }

    public string cdiendvm { get; set; }

    public string tpelevis { get; set; }

    public short qtdiasec { get; set; }

    public short qtdiasvd { get; set; }

    public decimal pcmindef { get; set; }

    public string tpfpelis { get; set; }

    public string cdiimcgp { get; set; }

    public string cdiimcgr { get; set; }

    public string cdestobj { get; set; }

    public System.DateTime dtatuali { get; set; }

    public System.DateTime dtlimper { get; set; }

    public System.DateTime dtaprova { get; set; }

    public string cdimptax { get; set; }

    public string cdicusta { get; set; }

    public short cdrmencb { get; set; }

    public short cdrmprmi { get; set; }

    public short cdrmreno { get; set; }

    public Nullable<short> cdobjpro { get; set; }

    public decimal pccomant { get; set; }

    public short qtdialimatsp { get; set; }

    public decimal pcdiaats { get; set; }

    public decimal vlmgdifbaixa { get; set; }

    public string tpajuven { get; set; }

    public decimal vllimmaxrisd { get; set; }

    public Nullable<short> cdlimmaxrisd { get; set; }

    public short cdrmsin { get; set; }

    public string indsalv { get; set; }

    public string indress { get; set; }

    public Nullable<short> qtdiasper { get; set; }

    public Nullable<decimal> vlmulta { get; set; }

    public string cdvermn { get; set; }

    public string cdprcsusep { get; set; }

    public Nullable<short> paramDependentes { get; set; }

}

}
