
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Projeto.Infra.DataContext
{

using System;
    using System.Collections.Generic;
    
public partial class vPlanoInd
{

    public short cdprodut { get; set; }

    public System.DateTime dtinivig { get; set; }

    public short nrseqplnind { get; set; }

    public string dsplnind { get; set; }

    public short tpplnand { get; set; }

    public decimal vllimcjgbas { get; set; }

    public string inresemg { get; set; }

    public decimal vlresemg { get; set; }

    public decimal pcfilisbas { get; set; }

    public decimal pcfilprebas { get; set; }

    public short tpsal { get; set; }

    public short qthormes { get; set; }

    public short qtsalbas { get; set; }

    public short tpfreqpl { get; set; }

    public short cdrefmon { get; set; }

    public short cdcobert { get; set; }

    public decimal pciscobbas { get; set; }

    public decimal vllimis { get; set; }

    public Nullable<decimal> vllimismin { get; set; }

    public decimal pcprepur { get; set; }

    public short tpcobert { get; set; }

    public Nullable<int> cdidaini { get; set; }

    public Nullable<int> cdidafim { get; set; }

    public Nullable<decimal> pcprepur1 { get; set; }

    public Nullable<decimal> vllimis1 { get; set; }

    public Nullable<decimal> vllimismin1 { get; set; }

    public string nmprodut { get; set; }

    public string nmcobert { get; set; }

    public string nmaramos { get; set; }

    public string indfaixa { get; set; }

    public Nullable<decimal> vlcsfixo { get; set; }

    public Nullable<decimal> vlcsfixo1 { get; set; }

    public string inbeneficio { get; set; }

    public Nullable<decimal> vlbeneficio { get; set; }

    public Nullable<short> nrmaxparc { get; set; }

}

}
